INSERT INTO users (name, email, password_hash, role)
VALUES
    ('Admin User', 'admin@praveenmart.com', '$2a$10$8K1p/a0dL1LXMIgoEDFrwOdMQiP8eB3fO8Xo9J5LhQp0u81yWz47.', 'ADMIN'),
    ('Praveen Seller', 'seller@praveenmart.com', '$2a$10$8K1p/a0dL1LXMIgoEDFrwOdMQiP8eB3fO8Xo9J5LhQp0u81yWz47.', 'SELLER'),
    ('Aditya Buyer', 'buyer@praveenmart.com', '$2a$10$8K1p/a0dL1LXMIgoEDFrwOdMQiP8eB3fO8Xo9J5LhQp0u81yWz47.', 'BUYER');

INSERT INTO products (seller_id, name, description, price, stock_qty, category, image_url)
VALUES
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Minimalist Linen Shirt', 'Breathable, 100% organic French linen tailored shirt for timeless elegance and comfort in any season.', 499.00, 28, 'Fashion & Style', 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Handcrafted Indigo Cotton Kurta', 'Traditional hand-block printed indigo pure cotton kurta featuring breathable weave and Mandarin collar.', 399.00, 35, 'Fashion & Style', 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Classic Denim Trucker Jacket', 'Heavyweight organic cotton denim trucker jacket with vintage brass buttons and reinforced stitching.', 799.00, 15, 'Fashion & Style', 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Organic Cotton Oversized Hoodie', 'Plush fleece-lined organic cotton hoodie engineered for relaxed fit, warmth, and daily comfort.', 599.00, 42, 'Fashion & Style', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Tailored Wool Blend Blazer', 'Sophisticated slim-fit wool blend blazer designed with inner lining, flap pockets, and single-breasted front.', 999.00, 12, 'Fashion & Style', 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Ceramic Pour-Over Coffee Set', 'Handcrafted artisanal ceramic dripper with wooden collar, engineered for optimal heat retention and precision extraction.', 349.00, 14, 'Home & Kitchen', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Handmade Scented Soy Candle', 'Natural soy wax infused with wild sage, cedarwood, and bergamot essential oils with lead-free cotton wick.', 149.00, 45, 'Home & Kitchen', 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Artisanal Teak Wood Serving Board', 'Solid teak wood charcuterie and cutting board finished with food-grade natural mineral oils.', 299.00, 20, 'Home & Kitchen', 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Handwoven Macrame Wall Hanging', 'Intricate bohemian wall art hand-braided with 100% natural unbleached cotton cord on wooden dowel.', 249.00, 18, 'Home & Kitchen', 'https://images.unsplash.com/photo-1522758971460-1d21eed7dc1d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Japanese Cast Iron Tea Kettle', 'Traditional tetsubin cast iron teapot with stainless steel mesh strainer for rich aroma preservation.', 649.00, 10, 'Home & Kitchen', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Noise-Cancelling Studio Headphones', 'Precision acoustic drivers with active ambient sound cancellation, 40-hour battery life, and plush memory foam earcups.', 1299.00, 9, 'Electronics', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Ergonomic Mechanical Keyboard', 'Compact mechanical keyboard with hot-swappable switches, PBT keycaps, and customizable RGB backlighting.', 899.00, 22, 'Electronics', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Retro Wooden Bluetooth Speaker', 'Vintage styled wireless speaker featuring dual full-range audio drivers, deep bass radiator, and 12h playtime.', 499.00, 25, 'Electronics', 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Smart Fitness Tracker Watch', 'AMOLED HD display smartwatch with continuous heart rate monitoring, SpO2 sensor, and 14-day battery life.', 699.00, 30, 'Electronics', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Precision Wireless Gaming Mouse', 'Ultra-lightweight wireless optical mouse with 26K DPI sensor, PTFE feet, and zero-latency wireless connectivity.', 399.00, 16, 'Electronics', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Full Grain Leather Messenger Bag', 'Vegetable-tanned full-grain leather laptop messenger bag with padded compartments and solid brass hardware.', 899.00, 19, 'Accessories', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Classic Aviator Sunglasses', 'Polarized UV400 protective aviator sunglasses featuring lightweight metal alloy frames and scratch-resistant lenses.', 299.00, 40, 'Accessories', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Minimalist RFID Leather Wallet', 'Slim bifold genuine leather wallet with RFID blocking technology, 8 card slots, and currency pocket.', 199.00, 50, 'Accessories', 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Stainless Steel Chronograph Watch', 'Precision quartz movement watch with genuine leather strap, date window, and 50m water resistance.', 999.00, 14, 'Accessories', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'seller@praveenmart.com'), 'Canvas Travel Duffle Bag', 'Water-resistant heavy canvas weekender duffle bag with genuine leather accents and shoe compartment.', 549.00, 22, 'Accessories', 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&auto=format&fit=crop&q=80');

INSERT INTO reviews (product_id, user_id, rating, comment)
VALUES
    (1, (SELECT id FROM users WHERE email = 'buyer@praveenmart.com'), 5, 'Amazing fabric quality and perfect fit!'),
    (2, (SELECT id FROM users WHERE email = 'buyer@praveenmart.com'), 5, 'Very comfortable kurta for summer.'),
    (6, (SELECT id FROM users WHERE email = 'buyer@praveenmart.com'), 4, 'Brews smooth coffee every morning.'),
    (11, (SELECT id FROM users WHERE email = 'buyer@praveenmart.com'), 5, 'Outstanding sound clarity and active noise cancellation!');
