INSERT INTO users (name, email, password_hash, role)
VALUES
    ('Admin User', 'admin@praveenmart.com', '$2a$10$71gV/GvK/cPjp9JSspIF..MGh8ONmLjGn4YL.T44bRxG7rMvBVsT.', 'ADMIN');

INSERT INTO products (seller_id, name, description, price, stock_qty, category, image_url)
VALUES
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Minimalist Linen Shirt', 'Breathable, 100% organic French linen tailored shirt for timeless elegance and comfort in any season.', 499.00, 28, 'Fashion & Style', 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Handcrafted Indigo Cotton Kurta', 'Traditional hand-block printed indigo pure cotton kurta featuring breathable weave and Mandarin collar.', 399.00, 35, 'Fashion & Style', 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Classic Denim Trucker Jacket', 'Heavyweight organic cotton denim trucker jacket with vintage brass buttons and reinforced stitching.', 799.00, 15, 'Fashion & Style', 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Organic Cotton Oversized Hoodie', 'Plush fleece-lined organic cotton hoodie engineered for relaxed fit, warmth, and daily comfort.', 599.00, 42, 'Fashion & Style', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Tailored Wool Blend Blazer', 'Sophisticated slim-fit wool blend blazer designed with inner lining, flap pockets, and single-breasted front.', 999.00, 12, 'Fashion & Style', 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Ceramic Pour-Over Coffee Set', 'Handcrafted artisanal ceramic dripper with wooden collar, engineered for optimal heat retention and precision extraction.', 349.00, 14, 'Home & Kitchen', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Handmade Scented Soy Candle', 'Natural soy wax infused with wild sage, cedarwood, and bergamot essential oils with lead-free cotton wick.', 149.00, 45, 'Home & Kitchen', 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Handwoven Macrame Wall Hanging', 'Intricate bohemian wall art hand-braided with 100% natural unbleached cotton cord on wooden dowel.', 249.00, 18, 'Home & Kitchen', 'https://images.unsplash.com/photo-1522758971460-1d21eed7dc1d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Japanese Cast Iron Tea Kettle', 'Traditional tetsubin cast iron teapot with stainless steel mesh strainer for rich aroma preservation.', 649.00, 10, 'Home & Kitchen', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Noise-Cancelling Studio Headphones', 'Precision acoustic drivers with active ambient sound cancellation, 40-hour battery life, and plush memory foam earcups.', 1299.00, 9, 'Electronics', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Ergonomic Mechanical Keyboard', 'Compact mechanical keyboard with hot-swappable switches, PBT keycaps, and customizable RGB backlighting.', 899.00, 22, 'Electronics', 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Retro Wooden Bluetooth Speaker', 'Vintage styled wireless speaker featuring dual full-range audio drivers, deep bass radiator, and 12h playtime.', 499.00, 25, 'Electronics', 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Smart Fitness Tracker Watch', 'AMOLED HD display smartwatch with continuous heart rate monitoring, SpO2 sensor, and 14-day battery life.', 699.00, 30, 'Electronics', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Precision Wireless Gaming Mouse', 'Ultra-lightweight wireless optical mouse with 26K DPI sensor, PTFE feet, and zero-latency wireless connectivity.', 399.00, 16, 'Electronics', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Full Grain Leather Messenger Bag', 'Vegetable-tanned full-grain leather laptop messenger bag with padded compartments and solid brass hardware.', 899.00, 19, 'Accessories', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Classic Aviator Sunglasses', 'Polarized UV400 protective aviator sunglasses featuring lightweight metal alloy frames and scratch-resistant lenses.', 299.00, 40, 'Accessories', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Minimalist RFID Leather Wallet', 'Slim bifold genuine leather wallet with RFID blocking technology, 8 card slots, and currency pocket.', 199.00, 50, 'Accessories', 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Stainless Steel Chronograph Watch', 'Precision quartz movement watch with genuine leather strap, date window, and 50m water resistance.', 999.00, 14, 'Accessories', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Canvas Travel Duffle Bag', 'Water-resistant heavy canvas weekender duffle bag with genuine leather accents and shoe compartment.', 549.00, 22, 'Accessories', 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Pure Mulberry Silk Scarf', 'Hand-woven 100% pure mulberry silk scarf with delicate floral hand-painted motifs and hand-rolled edges.', 1199.00, 25, 'Fashion & Style', 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Merino Wool Cable-Knit Sweater', 'Chunky knit crewneck sweater crafted from ultra-soft Australian Merino wool for natural warmth.', 1499.00, 18, 'Fashion & Style', 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Linen Casual Chino Trousers', 'Lightweight breathable linen blend relaxed fit trousers with drawstring waist and deep side pockets.', 699.00, 30, 'Fashion & Style', 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Ultra-Slim Wireless Power Bank 10000mAh', '20W fast-charging magnetic wireless power bank with aluminum unibody and digital battery display.', 799.00, 35, 'Electronics', 'https://images.unsplash.com/photo-1609592426868-b76504a79c94?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), '4K Ultra HD Webcam with Ring Light', 'Autofocus 60FPS streaming webcam with adjustable color temperature ring light and dual stereo mics.', 1199.00, 20, 'Electronics', 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'True Wireless Earbuds with ANC', 'Ergonomic in-ear buds with hybrid active noise cancellation, transparency mode, and 32h playback.', 899.00, 40, 'Electronics', 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Portable RGB Gaming Soundbar', 'Compact desktop soundbar with dynamic reactive RGB backlighting, Bluetooth 5.3, and dual aux.', 599.00, 28, 'Electronics', 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Handmade Stoneware Dinner Set (12 Pcs)', 'Artisanal matte-glazed ceramic dinner plates, salad plates, and bowls fired at high temperatures.', 1899.00, 12, 'Home & Kitchen', 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Cold Brew Iced Coffee Maker 1L', 'Borosilicate glass pitcher with extra-fine stainless steel mesh infuser and airtight silicone seal.', 449.00, 22, 'Home & Kitchen', 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Aromatherapy Ultrasonic Diffuser', 'Natural wood grain finish ultrasonic essential oil diffuser with 7 ambient LED mood lighting colors.', 399.00, 32, 'Home & Kitchen', 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Culinary Stainless Steel Chef Knife 8 Inch', 'High carbon German stainless steel kitchen knife with precision forged edge and Pakkawood handle.', 749.00, 16, 'Home & Kitchen', 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Polarized Sport Wrap Sunglasses', 'Ultra-durable TR90 frame with UV400 mirror polarized shatterproof lenses for cycling and running.', 349.00, 45, 'Accessories', 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Waterproof Laptop Backpack 25L', 'Anti-theft expandable travel backpack with padded laptop sleeve, USB charging port, and water-repellent shell.', 999.00, 25, 'Accessories', 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Genuine Leather Smartwatch Band', 'Hand-stitched top-grain vintage leather strap with brushed stainless steel buckle for 20mm/22mm watches.', 399.00, 30, 'Accessories', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Thermal Insulated Travel Flask 750ml', 'Double-wall vacuum insulated stainless steel water bottle keeping beverages hot for 12h and cold for 24h.', 299.00, 50, 'Accessories', 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Smart LED Desk Lamp with Wireless Qi Charger', 'Architectural dimmable LED task lamp with touch slider, 5 color modes, USB-C port, and 15W Qi wireless charging base.', 1299.00, 24, 'Electronics', 'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Ultra-Fast 1TB Portable External SSD', 'Rugged USB 3.2 Gen 2 aluminum pocket solid state drive with up to 1050MB/s transfer speeds and hardware encryption.', 2499.00, 15, 'Electronics', 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Dual-Band Wi-Fi 6 Gigabit Mesh Router', 'Next-gen Wi-Fi 6 wireless router with 4 high-gain antennas, WPA3 security, OFDMA, and seamless whole-home coverage.', 1599.00, 18, 'Electronics', 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Magnetic Car Phone Mount with 15W MagSafe Charging', 'Vent-mounted aerospace alloy phone holder with 360-degree rotation and auto-aligning magnetic fast charging.', 499.00, 40, 'Electronics', 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Oxford Button-Down Chambray Dress Shirt', 'Tailored cotton chambray shirt featuring mother-of-pearl buttons, button-down collar, and reinforced box pleat.', 749.00, 32, 'Fashion & Style', 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Handcrafted Italian Suede Penny Loafers', 'Classic slip-on penny loafers in supple vegetable-dyed suede with cushioned calfskin insole and rubber outsole.', 1899.00, 14, 'Fashion & Style', 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Double-Breasted Heritage Trench Coat', 'Water-resistant gabardine cotton trench coat with raglan sleeves, storm flap, horn buttons, and waist belt.', 2299.00, 10, 'Fashion & Style', 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Japanese Selvedge Raw Denim 14oz Jeans', 'Narrow loom shuttle-woven raw indigo selvedge denim jeans with copper rivets and button fly.', 1399.00, 20, 'Fashion & Style', 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Enameled Cast Iron Dutch Oven 5.5 Qt', 'Heavy-duty cast iron round Dutch oven with vibrant porcelain enamel exterior, tight-fitting lid, and stainless steel knob.', 2199.00, 12, 'Home & Kitchen', 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Electric Gooseneck Variable Temperature Kettle', 'Matte black stainless steel pour-over kettle with 1-degree precision digital temp dial, LCD display, and 1h hold.', 1299.00, 16, 'Home & Kitchen', 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Organic Turkish Cotton Bath Sheet Set (2 Pcs)', 'Ultra-absorbent 700 GSM combed long-staple Turkish cotton oversized bath towels with ribbed border.', 849.00, 28, 'Home & Kitchen', 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Artisan Acacia Wood Salad Bowl with Servers', 'Hand-turned natural acacia hardwood large salad serving bowl with matching ergonomic serving spoons.', 599.00, 22, 'Home & Kitchen', 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80'),

    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Aircraft Aluminum Carry-On Spinner Suitcase', 'Hard-shell anodized aluminum 20-inch carry-on luggage with dual TSA combination locks and silent 360 wheels.', 3499.00, 8, 'Accessories', 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600&auto=format&fit=crop&q=80'),
    ((SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 'Natural Cork & Rubber Non-Slip Fitness Mat', 'Eco-friendly sustainable cork surface with natural tree rubber base for superior wet and dry grip yoga and pilates.', 699.00, 25, 'Accessories', 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80');

INSERT INTO reviews (product_id, user_id, rating, comment)
VALUES
    (1, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 5, 'Amazing fabric quality and perfect fit!'),
    (2, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 5, 'Very comfortable kurta for summer.'),
    (6, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 4, 'Brews smooth coffee every morning.'),
    (11, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 5, 'Outstanding sound clarity and active noise cancellation!'),
    (24, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 5, 'Super compact power bank, charges fast!'),
    (36, (SELECT id FROM users WHERE email = 'admin@praveenmart.com'), 5, 'The desk lamp is stunning and wireless charging is seamless.');
